[build]
  base = "."
  publish = "client/build"
  command = "cd client && npm install && CI=false npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.16.0"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[dev]
  functions = "netlify/functions"
  publish = "client/build"
  
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/manifest.json"
    [headers.values]
    Content-Type = "application/json"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
