[functions]
external_node_modules = ["sharp", "fluent-ffmpeg", "mongodb-client-encryption", "bson", "aws4", "mongoose", "file-type", "image-size"]
included_files = ["node_modules/sharp/**/*", "node_modules/fluent-ffmpeg/**/*"]
node_bundler = "esbuild"

[functions."*"]
timeout = 60

[build]
command = "GENERATE_SOURCEMAP=false CI=false npm run build"
publish = "build"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "18.16.0"
NODE_ENV = "production"
CI = "false"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = """
  default-src 'self';
  script-src 'self' 'unsafe-inline' 'unsafe-eval';
  style-src 'self' 'unsafe-inline';
  img-src 'self' data: blob: https:;
  media-src 'self' data: blob: https:;
  connect-src 'self' https:;
  font-src 'self';
  object-src 'none';
  frame-ancestors 'none';
  form-action 'self';
  base-uri 'self';
"""
