[build]
  base = "community-mass-mems"
  command = "npm install --legacy-peer-deps && CI=false DISABLE_ESLINT_PLUGIN=true npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  CI = "false"
  NODE_ENV = "production"
  NETLIFY = "true"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = [
    "sharp",
    "fluent-ffmpeg",
    "mongodb-client-encryption",
    "bson",
    "aws4",
    "mongoose",
    "file-type",
    "image-size",
    "unfurl.js",
    "page-metadata-parser",
    "domino",
    "node-fetch",
    "busboy",
    "cors",
    "dotenv",
    "express",
    "path",
    "canvas",
    "jsdom"
  ]

[functions."*"]
  included_files = ["node_modules/sharp/**/*", "node_modules/fluent-ffmpeg/**/*"]
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "canvas"]

[functions.uploadUrl]
  included_files = ["node_modules/**/*"]
  external_node_modules = ["sharp", "canvas", "node-fetch", "mongoose"]

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      img-src 'self' data: blob: http: https: *.tiktokcdn.com *.fbcdn.net;
      media-src 'self' data: blob: http: https: *.tiktokcdn.com;
      object-src 'none';
      frame-src 'self' 
        https://www.youtube.com 
        https://youtube.com
        https://www.facebook.com 
        https://platform.twitter.com
        https://syndication.twitter.com
        https://www.instagram.com
        https://player.vimeo.com
        https://w.soundcloud.com
        https://open.spotify.com
        https://www.tiktok.com;
      style-src 'self' 'unsafe-inline' 
        https://fonts.googleapis.com
        https://cdnjs.cloudflare.com
        https://use.fontawesome.com;
      font-src 'self' 
        https://fonts.gstatic.com
        https://cdnjs.cloudflare.com
        https://use.fontawesome.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval'
        https://www.youtube.com
        https://s.ytimg.com
        https://platform.twitter.com
        https://cdn.syndication.twimg.com
        https://connect.facebook.net
        https://www.instagram.com
        https://www.tiktok.com
        https://cdnjs.cloudflare.com;
      connect-src 'self' 
        https://api.twitter.com
        https://syndication.twitter.com
        https://platform.twitter.com
        https://vimeo.com
        https://api.vimeo.com
        https://w.soundcloud.com
        https://api.soundcloud.com
        https://open.spotify.com
        https://api.spotify.com
        https://www.facebook.com
        https://graph.facebook.com
        https://www.instagram.com
        https://api.instagram.com
        https://www.tiktok.com
        https://api.tiktok.com
        data: blob: http: https:;"""
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  AZURE_TENANT_ID = "Azure AD tenant ID"
  AZURE_CLIENT_ID = "Azure AD application client ID"
  AZURE_CLIENT_SECRET = "Azure AD application client secret"
  ONEDRIVE_DRIVE_ID = "OneDrive drive ID"
  ONEDRIVE_FOLDER_ID = "OneDrive folder ID for storing files"
  EMAIL_USER = "Email address for notifications"
  EMAIL_PASSWORD = "Email password for notifications"
  MONGODB_URI = "Your MongoDB connection string"
  GROQ_API_KEY = "Your GROQ API key for content moderation"
