[functions]
external_node_modules = ["sharp", "fluent-ffmpeg", "mongodb-client-encryption", "bson", "aws4", "mongoose", "file-type", "image-size", "unfurl.js", "page-metadata-parser", "domino", "node-fetch", "busboy", "cors", "dotenv", "express", "path"]
included_files = ["node_modules/sharp/**/*", "node_modules/fluent-ffmpeg/**/*"]
node_bundler = "esbuild"
directory = "netlify/functions"

[functions."*"]
timeout = 30
memory = 1024

[build]
base = "community-mass-mems"
command = "npm install && CI=false npm run build"
publish = "build"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "18.16.0"
NODE_ENV = "production"
CI = "false"

[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = """
  default-src 'self';
  img-src 'self' data: blob: http: https: *.tiktokcdn.com *.fbcdn.net;
  media-src 'self' data: blob: http: https: *.tiktokcdn.com;
  object-src 'none';
  frame-src 'self' 
    https://www.youtube.com 
    https://youtube.com
    https://www.facebook.com 
    https://platform.twitter.com
    https://syndication.twitter.com
    https://www.instagram.com
    https://www.tiktok.com
    https://player.vimeo.com
    https://www.pinterest.com;
  connect-src 'self' 
    https://*.facebook.com 
    https://*.fbcdn.net
    https://api.twitter.com
    https://syndication.twitter.com
    https://cdn.syndication.twimg.com
    https://api.instagram.com
    https://graph.instagram.com
    https://api.tiktok.com
    https://www.tiktok.com
    https://api.pinterest.com
    https://api.vimeo.com
    http: https:;
  style-src 'self' 'unsafe-inline' 
    https://platform.twitter.com
    https://ton.twimg.com
    https://www.tiktok.com
    https://www.instagram.com
    https://www.facebook.com
    https:;
  script-src 'self' 'unsafe-inline' 'unsafe-eval'
    https://connect.facebook.net
    https://platform.twitter.com
    https://www.instagram.com
    https://www.tiktok.com
    https://assets.pinterest.com
    https://player.vimeo.com
    https:;
  font-src 'self' data: https:;
  worker-src 'self' blob:;
"""
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
for = "/*.jpg"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.jpeg"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.gif"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.webp"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.ico"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.woff2"
[headers.values]
Cache-Control = "public, max-age=31536000"
