[build]
  base = "community-mass-mems"
  command = "npm install --legacy-peer-deps && CI=false DISABLE_ESLINT_PLUGIN=true bash ./build.sh"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  CI = "false"
  NODE_ENV = "production"
  NETLIFY = "true"
  SITE_URL = "https://shiny-jalebi-9ccb2b.netlify.app"
  MONGODB_URI = "mongodb+srv://davidpthomsen:Gamer6688@cluster0.rz2oj.mongodb.net/memories?authSource=admin&retryWrites=true&w=majority&appName=Cluster0"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "@mongodb-js/zstd", "bson", "mongodb-client-encryption", "snappy", "aws4"]

[functions."*"]
  included_files = ["node_modules/mongodb/**/*", "node_modules/@mongodb-js/**/*", "node_modules/bson/**/*"]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "@mongodb-js/zstd", "bson", "mongodb-client-encryption"]

[functions.uploadUrl]
  included_files = ["node_modules/mongodb/**/*", "node_modules/@mongodb-js/**/*", "node_modules/bson/**/*"]
  external_node_modules = ["mongodb", "@mongodb-js/zstd", "bson", "mongodb-client-encryption"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "https://r1memories.com/*"
  to = "https://shiny-jalebi-9ccb2b.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  MONGODB_URI = "Your MongoDB connection string"
  OPENAI_API_KEY = "Your OpenAI API key for content moderation"
