[functions]
external_node_modules = ["sharp", "fluent-ffmpeg", "mongodb-client-encryption", "bson", "aws4", "mongoose", "file-type", "image-size", "unfurl.js", "page-metadata-parser", "domino", "node-fetch", "busboy", "cors", "dotenv", "express", "path"]
included_files = ["node_modules/sharp/**/*", "node_modules/fluent-ffmpeg/**/*"]
node_bundler = "esbuild"
directory = "netlify/functions"

[functions."*"]
timeout = 30
memory = 1024

[build]
command = "npm run build"
publish = "build"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "18.16.0"
NODE_ENV = "production"
CI = "false"

[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = """
  default-src 'self';
  img-src 'self' data: http: https:;
  media-src 'self' data: http: https:;
  object-src 'self' http: https:;
  frame-src 'self' http: https:;
  connect-src 'self' http: https:;
  style-src 'self' 'unsafe-inline' https:;
  script-src 'self' 'unsafe-inline' 'unsafe-eval' https:;
  font-src 'self' data: https:;
"""
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
for = "/*.jpg"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.jpeg"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.gif"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.webp"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.mp4"
[headers.values]
Cache-Control = "public, max-age=31536000"
Content-Type = "video/mp4"

[[headers]]
for = "/*.webm"
[headers.values]
Cache-Control = "public, max-age=31536000"
Content-Type = "video/webm"

[[headers]]
for = "/*.mp3"
[headers.values]
Cache-Control = "public, max-age=31536000"
Content-Type = "audio/mpeg"

[[headers]]
for = "/*.wav"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.pdf"
[headers.values]
Cache-Control = "public, max-age=31536000"
Content-Type = "application/pdf"
