[build]
  base = "community-mass-mems"
  command = "npm install --legacy-peer-deps && CI=false DISABLE_ESLINT_PLUGIN=true npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"
  CI = "false"
  NODE_ENV = "production"
  NETLIFY = "true"
  SITE_URL = "https://shiny-jalebi-9ccb2b.netlify.app"
  MONGODB_URI = "mongodb+srv://davidpthomsen:Gamer6688@cluster0.rz2oj.mongodb.net/memories?authSource=admin&retryWrites=true&w=majority&appName=Cluster0"
  GROQ_API_KEY = "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"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "@mongodb-js/zstd", "bson", "mongodb-client-encryption", "snappy", "aws4"]

[functions."*"]
  included_files = ["node_modules/mongodb/**/*", "node_modules/@mongodb-js/**/*", "node_modules/bson/**/*"]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb", "@mongodb-js/zstd", "bson", "mongodb-client-encryption"]

[functions.uploadUrl]
  included_files = ["node_modules/mongodb/**/*", "node_modules/@mongodb-js/**/*", "node_modules/bson/**/*"]
  external_node_modules = ["mongodb", "@mongodb-js/zstd", "bson", "mongodb-client-encryption"]

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      img-src 'self' data: blob: http: https: *.tiktokcdn.com *.fbcdn.net;
      media-src 'self' data: blob: http: https: *.tiktokcdn.com;
      object-src 'none';
      frame-src 'self' 
        https://*.youtube.com 
        https://*.facebook.com 
        https://*.twitter.com
        https://*.instagram.com
        https://*.vimeo.com
        https://*.soundcloud.com
        https://*.spotify.com
        https://*.tiktok.com;
      style-src 'self' 'unsafe-inline' https://*.googleapis.com https://*.cloudflare.com https://*.fontawesome.com;
      style-src-elem 'self' 'unsafe-inline' https://*.googleapis.com https://*.cloudflare.com https://*.fontawesome.com;
      font-src 'self' data: https://*.gstatic.com https://*.cloudflare.com https://*.fontawesome.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
        https://*.youtube.com
        https://*.facebook.com
        https://*.twitter.com
        https://*.instagram.com
        https://*.tiktok.com
        https://*.cloudflare.com
        https://connect.facebook.net;
      script-src-elem 'self' 'unsafe-inline'
        https://*.youtube.com
        https://*.facebook.com
        https://*.twitter.com
        https://*.instagram.com
        https://*.tiktok.com
        https://*.cloudflare.com
        https://connect.facebook.net;
      connect-src 'self' 
        https://api.twitter.com
        https://syndication.twitter.com
        https://platform.twitter.com
        https://vimeo.com
        https://api.vimeo.com
        https://w.soundcloud.com
        https://api.soundcloud.com
        https://open.spotify.com
        https://api.spotify.com
        https://www.facebook.com
        https://graph.facebook.com
        https://www.instagram.com
        https://api.instagram.com
        https://www.tiktok.com
        https://api.tiktok.com
        https://*.mongodb.net
        https://*.mongodb-api.com
        https://r1memories.com
        https://www.r1memories.com
        https://shiny-jalebi-9ccb2b.netlify.app
        data: blob: http: https:;"""
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

[[redirects]]
  from = "https://r1memories.com/*"
  to = "https://shiny-jalebi-9ccb2b.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  MONGODB_URI = "Your MongoDB connection string"
  GROQ_API_KEY = "Your GROQ API key for content moderation"
