[functions]
external_node_modules = ["sharp", "fluent-ffmpeg", "mongodb-client-encryption", "bson", "aws4", "mongoose", "file-type", "image-size", "unfurl.js", "page-metadata-parser", "domino", "node-fetch", "busboy", "cors", "dotenv", "express", "path"]
included_files = ["node_modules/sharp/**/*", "node_modules/fluent-ffmpeg/**/*"]
node_bundler = "esbuild"
directory = "netlify/functions"

[functions."*"]
timeout = 30
memory = 1024

[build]
command = "GENERATE_SOURCEMAP=false CI=false npm run build"
publish = "build"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "18.16.0"
NODE_ENV = "production"
CI = "false"

[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = """
  default-src 'self';
  script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*;
  style-src 'self' 'unsafe-inline' https://*;
  img-src 'self' data: blob: https://* http://*;
  font-src 'self' data: https://*;
  frame-src https://* http://*;
  connect-src 'self' https://* http://*;
  media-src 'self' blob: https://* http://*;
  object-src 'self' https://* http://*;
"""

[[headers]]
for = "/*.mp3"
[headers.values]
Cache-Control = "public, max-age=31536000"
Content-Type = "audio/mpeg"

[[headers]]
for = "/*.mp4"
[headers.values]
Cache-Control = "public, max-age=31536000"
Content-Type = "video/mp4"

[[headers]]
for = "/*.webm"
[headers.values]
Cache-Control = "public, max-age=31536000"
Content-Type = "video/webm"

[[headers]]
for = "/*.pdf"
[headers.values]
Cache-Control = "public, max-age=31536000"
Content-Type = "application/pdf"
