[functions]
external_node_modules = ["sharp", "fluent-ffmpeg", "mongodb-client-encryption", "bson", "aws4", "mongoose", "file-type", "image-size", "unfurl.js", "page-metadata-parser", "domino", "node-fetch", "busboy", "cors", "dotenv", "express", "path"]
included_files = ["node_modules/sharp/**/*", "node_modules/fluent-ffmpeg/**/*"]
node_bundler = "esbuild"
directory = "../netlify/functions"

[functions."*"]
timeout = 30
memory = 1024

[build]
command = "GENERATE_SOURCEMAP=false CI=false npm run build"
publish = "build"
functions = "../netlify/functions"

[build.environment]
NODE_VERSION = "18.16.0"
NODE_ENV = "production"
CI = "false"

[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = """
  default-src 'self';
  script-src 'self' 'unsafe-inline' 'unsafe-eval' 
    https://*.twitter.com 
    https://*.instagram.com 
    https://*.tiktok.com 
    https://*.facebook.com 
    https://*.facebook.net 
    https://*.redditmedia.com 
    https://*.reddit.com
    https://w.soundcloud.com
    https://connect.facebook.net
    https://platform.twitter.com
    https://www.youtube.com
    https://player.vimeo.com
    https://app.suno.ai
    https://r1prompts.com
    https://discord.com;
  style-src 'self' 'unsafe-inline' 
    https://*.twitter.com
    https://*.instagram.com
    https://*.tiktok.com
    https://*.facebook.com
    https://*.redditmedia.com;
  img-src 'self' data: blob: 
    https://*.twitter.com
    https://*.twimg.com
    https://*.instagram.com
    https://*.fbcdn.net
    https://*.tiktokcdn.com
    https://*.redditmedia.com
    https://*.redditstatic.com
    https://*.vimeocdn.com
    https://*.ytimg.com
    https://*.soundcloud.com
    https://*.sndcdn.com
    https://*.spotify.com
    https://*.discordapp.com
    https://*.r1prompts.com
    https://*.suno.ai;
  font-src 'self' data:;
  frame-src
    https://*.twitter.com
    https://*.instagram.com
    https://*.tiktok.com
    https://*.facebook.com
    https://*.reddit.com
    https://*.redditmedia.com
    https://w.soundcloud.com
    https://open.spotify.com
    https://www.youtube.com
    https://player.vimeo.com
    https://discord.com
    https://r1prompts.com
    https://app.suno.ai;
  connect-src 'self'
    https://*.twitter.com
    https://*.instagram.com
    https://*.tiktok.com
    https://*.facebook.com
    https://*.reddit.com
    https://*.redditmedia.com
    https://w.soundcloud.com
    https://api.spotify.com
    https://www.youtube.com
    https://player.vimeo.com
    https://discord.com
    https://r1prompts.com
    https://app.suno.ai;
  media-src 'self'
    blob:
    https://*.twitter.com
    https://*.instagram.com
    https://*.tiktok.com
    https://*.facebook.com
    https://*.reddit.com
    https://*.redditmedia.com
    https://*.soundcloud.com
    https://*.sndcdn.com
    https://*.spotify.com
    https://*.youtube.com
    https://*.vimeocdn.com
    https://discord.com
    https://r1prompts.com
    https://app.suno.ai;
"""

[[headers]]
for = "/*.mp3"
[headers.values]
Cache-Control = "public, max-age=31536000"
Content-Type = "audio/mpeg"
