[functions]
external_node_modules = ["sharp", "fluent-ffmpeg", "mongodb-client-encryption", "bson", "aws4", "mongoose", "file-type", "image-size"]
included_files = ["node_modules/sharp/**/*", "node_modules/fluent-ffmpeg/**/*"]
node_bundler = "esbuild"

[functions."*"]
timeout = 30

[build]
command = "GENERATE_SOURCEMAP=false CI=false npm run build"
publish = "build"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "18.16.0"
NODE_ENV = "production"
CI = "false"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval';"
