[functions]
external_node_modules = ["sharp", "fluent-ffmpeg", "mongodb-client-encryption", "bson", "aws4", "mongoose", "file-type", "image-size", "unfurl.js", "page-metadata-parser", "domino", "node-fetch", "busboy", "cors", "dotenv", "express", "path"]
included_files = ["node_modules/sharp/**/*", "node_modules/fluent-ffmpeg/**/*"]
node_bundler = "esbuild"
directory = "netlify/functions"

[functions."*"]
timeout = 30
memory = 1024

[build]
base = "community-mass-mems"
command = "npm install && CI=false npm run build"
publish = "build"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "18.17.0"
NODE_ENV = "production"
CI = "false"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = """
  default-src 'self';
  img-src 'self' data: blob: http: https: *.tiktokcdn.com *.fbcdn.net;
  media-src 'self' data: blob: http: https: *.tiktokcdn.com;
  object-src 'none';
  frame-src 'self' 
    https://www.youtube.com 
    https://youtube.com
    https://www.facebook.com 
    https://platform.twitter.com
    https://syndication.twitter.com
    https://www.instagram.com
    https://player.vimeo.com
    https://w.soundcloud.com
    https://open.spotify.com;
  style-src 'self' 'unsafe-inline';
  script-src 'self' 'unsafe-inline' 'unsafe-eval'
    https://www.youtube.com
    https://s.ytimg.com
    https://platform.twitter.com
    https://cdn.syndication.twimg.com;
  connect-src 'self' 
    https://api.twitter.com
    https://syndication.twitter.com
    https://platform.twitter.com
    https://vimeo.com
    https://api.vimeo.com
    https://w.soundcloud.com
    https://api.soundcloud.com
    https://open.spotify.com
    https://api.spotify.com
    data: blob: http: https:;
"""
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"
