services:
  - type: web
    name: r1-memories-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
